version: "3.9"
services:
  app:
    container_name: task-register-deploy
    build:
      context: .
      target: deploy
    image: task-register:deploy
    environment:
      NODE_ENV: production
      LAMBDA_ENV: deploy
      REGION: ${REGION}
      STAGE: ${STAGE}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_USER_TOKEN: ${SLACK_USER_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
