version: "3.9"
services:
  app:
    container_name: task-register
    build:
      context: .
      target: test
    image: task-register:test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      LAMBDA_ENV: test
      REGION: ${REGION}
      STAGE: ${STAGE}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_USER_TOKEN: ${SLACK_USER_TOKEN}
