# NOTE: update this with your service name
service: task-register

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000
  bundle:
    tsConfig: "tsconfig.eslint.json"
    linting: false

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 30
  role: arn:aws:iam::051826142769:role/lambda-task-registration-role
  apiKeys:
    - companyInternalUsagePlan:
      - company-internal-shared-key # this key can be used for a Custom Authorizer
  usagePlan:
    - companyInternalUsagePlan:
        throttle:
          burstLimit: 100
          rateLimit: 200
        quota:
          limit: 200_000
          period: MONTH

  environment:
    STAGE: ${opt:stage}
    REGION: ${opt:region}
    LAMBDA_ENV: ${env:LAMBDA_ENV}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_USER_TOKEN: ${env:SLACK_USER_TOKEN}

functions:
  slackEvents:
    handler: src/slackbot.events
    events:
      - http:
          path: slack/events
          method: post
  registerTasks:
    handler: src/task.registerTasks
    events:
      - http:
          path: tasks
          method: post
          cors: false
  getTasks:
    handler: src/task.getTasks
    events:
      - http:
          path: tasks/{employeeId}
          method: get
          cors: false
