version: "3.9"
services:
  app:
    container_name: task-register
    build:
      context: .
    image: task-register:local
    ports: 
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
  ngrok:
    image: wernight/ngrok:latest
    ports: 
      - 4040:4040
    depends_on:
      - app
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: app:4000
      NGROK_AUTH: ${NGROK_AUTH} # https://dashboard.ngrok.com/get-started/your-authtoken
