version: "3.9"
services:
  app:
    container_name: task-registerapp
    build:
      context: .
    image: task-registerapp:local
    ports: 
      - 4000:4000
    volumes:
      - ./:/app
