version: "3.9"
services:
  app:
    container_name: task-register
    build:
      context: .
    image: task-register:local
    ports:
      - 4000:4000
    volumes:
      - ./:/app

#todo: Hot reloading using Docker is not fully tested yet (without Docker is working fine
