# NOTE: update this with your service name
service: task-register

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}



functions:
  registerTasks:
    handler: task.registerTasks
    events:
      - http:
          path: tasks
          method: post
  getTasks:
    handler: task.getTasks
    events:
      - http:
          path: tasks
          method: get
